### ISSUE TITLE
DriverGamepad has bug that causes the drive base to continue to drive slowly when axis is centered.

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/newarch#18]
Fix the bug with the drivebase driving when the axis is centered.

**Comment by sjcbulldog** [comment]
Fixed this bug which could level the drivebase running at a very slow speed even then the driver has released the axis that control the drive base.

**Comment by 1425** [comment]
When we've had this issue in the past it's been because the gamepad thought that wherever it happened to be when it was initialized was zero, but that point was not centered.  Specifically, this most often happened if the gamepad got plugged in before the wire had been unwrapped, and the wires held the stick slightly to the side.  This may or may not be what you saw, but might be a way to test it regardless.

**Comment by sjcbulldog** [comment]
The issue here was the logic in the driver gamepad had a bug.  Basically the new architecture works by assigning actions to subsystem.  However, to keep the traffic down, the driver gamepad only assigns a new action if the desired left or right power has changed greater than a threshold.  Couple this with the fact that the TalonSRX have a deadband.  So there was a very narrow region between the deadband region of the TalonSRX and the threshold for new actions from the gamepad that could leave the drivebase with and action of very low power.  Fixed this by just adding a deadband threshold to the gamepad.
