### ISSUE TITLE
Use the current limiting capabilities of the TalonSRX motor controllers to limit drivebase current

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/newarch#4]
The TalonSRX motor controllers have a current limiting capability.  We should use this capability in the drive base to reduce the chances of a motor burning out.

**Comment by 1425** [comment]
Note that different kinds of motors have very different characteristics as far as how easy they are to burn out.  While a 775 can burn out in a few seconds, a CIM, which is what we have used in our drive bases every years since 2005, does not have this same susceptibility.  The short-term amount of power that they can handle exceeds what the rest of the electrical system can supply.  

If we were to do a 775-based gearbox then this would be a good idea.  If we are usings CIMs again, the limit that is needed to keep them from burning out is likely to be so high that it will never be observed.

**Comment by sjcbulldog** [comment]
Not going to do.
