### ISSUE TITLE
Be able to place hatches from the side on the cargo ship 

### ISSUE THREAD

**Issue by tcavarno** [errorcodexero/newarch#68]

**Comment by sjcbulldog** [comment]
This is not possible with the current hatch holder design.

**Comment by 1425** [comment]
What goes wrong when attempting this with the hatch holder?  I don't understand why this would not be possible - or why it would even take anything special.  

On the other hand, I can see this being something that we use only infrequently so maybe it's not worth worrying about.

**Comment by sjcbulldog** [comment]
In order to close the hooks holding the hatch, we need to detect that we hit the target.  For front and back we use the motion of the robot to do this.  On the sides (since our robot does not move sideways) we would have to use the motion of the arm.  This means we have to be positioned in the range of distance where the robot is close enough that we don't reach full extension, which is difficult to do with the fairly short range of motion of that piston.  So, I guess its not impossible, but difficult enough to do and not needed enough that we should spend time on it.

**Comment by 1425** [comment]
I might be tempted to just try it once to see if it works with no changes.  The robot being skinnier than it is long effectively increases reach on the sides.  

I agree that this is low priority.  Strategically, we should have null hatches there unless we have a partner who's planning to do these themselves.
