### ISSUE TITLE
Ready action north not running concurrently

### ISSUE THREAD

**Issue by tcavarno** [errorcodexero/newarch#80]
Init robot condition: south, LS Height
What I did: pressed north then hit lvl. 1
What happened: turntable moved to the north position then dropped to lvl. 1
What I expected: rotate to north then start dropping down to lvl 1 the moment I press the height button

Notes: when I run the experiment starting at north lvl 2 and going to South lvl. 1 it runs concurrently as I would expect

**Comment by sjcbulldog** [comment]
Because the target height (11.5) is below the safe height (14.0) the ready action should do a rotate and lifter drop at the same time, but only down to the safe height (14.0).  Once this is complete, it should drop down to the target height (11.5).  It is not clear from the explanation if it does not drop at all during the rotation or does not drop all the way and has to finish the drop at the end (as designed).  If it is not dropping at all during the rotate, we can hopefully find time to debug in the pits at worlds.

**Comment by sjcbulldog** [comment]
No longer going to work on this as the season is over.
